name: SwiftWasm

on:
  push:
    branches:
      - master
      - wasm
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: Test SwiftWasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: swiftwasm/swiftwasm-action@master
        with:
          swift-action: build --triple wasm32-unknown-wasi
